[tool.ruff]
# Target Python 3.12
target-version = "py312"

# Set line length to 88 (same as black)
line-length = 88

# Enable all rules by default
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "ARG", # flake8-unused-arguments
    "PL",  # pylint
    "PT",  # flake8-pytest-style
]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (handled by formatter)
]

# Allow autofix behavior
fix = true
unsafe-fixes = true

# Exclude directories and files
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pycache__",
    "cdk.out",
    "node_modules",
]

# Assume Python 3.12
src = ["src", "infrastructure"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.isort]
known-first-party = ["src", "infrastructure"]
known-third-party = ["aws_cdk", "aws_lambda_powertools", "constructs"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true
force-wrap-aliases = true

[tool.ruff.pylint]
max-args = 6
max-statements = 50

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
# Ignore unused imports in __init__.py files
"__init__.py" = ["F401"]
# Ignore specific rules in test files
"tests/*" = ["PLR2004", "S101"]

[tool.ruff.pydocstyle]
convention = "google"